CREATE TABLE budgets
  ( b_id             INTEGER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY
  , amount           NUMBER(19, 4) NOT NULL
                      CONSTRAINT check_positive_budget_amount CHECK (amount >=0)
  , b_date           DATE NOT NULL
  , comments         VARCHAR2(255)
  , budget_category  INTEGER NOT NULL
  );

CREATE TABLE budget_categories
  ( b_cat_id        INTEGER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY
  , b_cat_name      VARCHAR2(30) NOT NULL UNIQUE
  );

CREATE TABLE income_categories
  ( inc_cat_id      INTEGER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY
  , inc_cat_name    VARCHAR2(100) NOT NULL UNIQUE
  );

CREATE TABLE expense_categories
  ( exp_cat_id      INTEGER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY
  , exp_name        VARCHAR2(100) NOT NULL
  , budget          INTEGER NOT NULL
  , CONSTRAINT exp_cat_uq UNIQUE (exp_name, budget)
  );

CREATE TABLE accounts
  ( acc_id          INTEGER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY
  , acc_name        VARCHAR2(30) NOT NULL UNIQUE
  , account_type    INTEGER NOT NULL
  , currency        INTEGER NOT NULL
  , current_state   NUMBER (19, 4) DEFAULT 0 NOT NULL
  , opened          DATE DEFAULT SYSDATE NOT NULL
  , closed          DATE
  , last_change     DATE NOT NULL
  , CONSTRAINT check_close_null_or_ge_open CHECK (
      closed IS NULL OR closed <= opened)
  );
  
CREATE TABLE currency
  ( curr_id         INTEGER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY 
  , curr_name       CHAR(3) NOT NULL
  );

CREATE TABLE incomes
  ( inc_id          INTEGER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY
  , amount          NUMBER(19, 4) NOT NULL
  , inc_date        DATE NOT NULL
  , comments        VARCHAR2(255)
  , income_category INTEGER NOT NULL
  , account         INTEGER NOT NULL
  );

CREATE TABLE account_types
  ( acc_type_id     INTEGER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY
  , acc_type_name   VARCHAR2(50) NOT NULL UNIQUE
  );

CREATE TABLE expenses
  ( exp_id          INTEGER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY
  , amount          NUMBER(19, 4) NOT NULL
                      CONSTRAINT check_positive_exp_amount CHECK (amount > 0)
  , exp_date        DATE NOT NULL
  , comments        VARCHAR2(255)
  , expense_category INTEGER NOT NULL
  , account         INTEGER NOT NULL
  );
